// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIlMJmsn0ynjG7upVr7QuoEoTSsGPev0',
    appId: '1:1084064449621:web:8ec59404b178ddddb980dc',
    messagingSenderId: '1084064449621',
    projectId: 'flutter-chat-d6ec9',
    authDomain: 'flutter-chat-d6ec9.firebaseapp.com',
    storageBucket: 'flutter-chat-d6ec9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjUdYDzkyK5wh1C8a7ORF6yU53c-F7Do',
    appId: '1:1084064449621:android:c362525ea30c10f4b980dc',
    messagingSenderId: '1084064449621',
    projectId: 'flutter-chat-d6ec9',
    storageBucket: 'flutter-chat-d6ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmxEPx7NQ9FbpC3W-3IdWudelwMnFnnA',
    appId: '1:1084064449621:ios:df23a807b1938f76b980dc',
    messagingSenderId: '1084064449621',
    projectId: 'flutter-chat-d6ec9',
    storageBucket: 'flutter-chat-d6ec9.appspot.com',
    iosClientId: '1084064449621-t20jqs9jj44m4mg49g6lrtms8othuvs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRmxEPx7NQ9FbpC3W-3IdWudelwMnFnnA',
    appId: '1:1084064449621:ios:df23a807b1938f76b980dc',
    messagingSenderId: '1084064449621',
    projectId: 'flutter-chat-d6ec9',
    storageBucket: 'flutter-chat-d6ec9.appspot.com',
    iosClientId: '1084064449621-t20jqs9jj44m4mg49g6lrtms8othuvs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
